[package]
name = "temple"
version = "0.1.0"
authors = ["Christopher Miller <cmiller548@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_rapier2d = "0.9.0"
kurinji = { git = "https://github.com/jacobjenks/kurinji", branch = "upgrade_bevy_0.5" }
bevy_tilemap = "0.4"
bevy_easings = "0.4.0"
bevy_egui = "0.4"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[features]
debug = []
