title = 'Temple'
authors = ['ALUMUX (Chris M)']
level_transistion = 'NoOverworld'
level_order = [0, 1]
credit_music = "walkintherain.ogg"
credits = '''
# Temple
---
Thanks for playing this dev build of Temple! This game has been a long-time work in progress and I hope you will play again when there is more to see :)



---
To leave the credits, exit the game.
'''
