version = 1

[[levels]]
id = 0
sprite_map = "levels/0.png"

[[levels.sprites]]
color = 0x000000
name = "boneyard_ground_middle"

[[levels.sprites]]
color = 0x111111
name = "boneyard_ground_center"

[[levels.sprites]]
color = 0xFFFFFF
name = "player"

[[levels.sprites]]
color = 0xFFFF00
name = "moving_platform_right_slow"

[[levels.sprites]]
color = 0xFFFF01
name = "moving_platform_left_slow"

[[levels.sprites]]
color = 0xFF0000
name = "checkpoint"

[[levels.sprites]]
color = 0x0000FF
name = "death_air"

[[levels.sprites]]
color = 0xFF0001
name = "skull_nomove"

[[levels.sprites]]
color = 0xFF0010
name = "skull_move_vertical"

[[levels.sprites]]
color = 0xFF00FF
name = "moving_platform_up_slow"
