name = 'Boneyard'
music = 'walkintherain.ogg'

[[sprites]]
name = 'checkpoint'
offset = [
    0,
    0,
]
texture = 'checkpoint.png'
attributes = ['checkpoint(0,0)']

[[sprites]]
name = 'skulls_idle'
offset = [
    0,
    0,
]
texture = 'skull.png'
attributes = ['deadly']

[[sprites]]
name = 'elevator'
offset = [
    0,
    0,
]
texture = 'boneyard/topmiddle.png'
attributes = [
    'moving(up,12,15)',
    'solid',
]

[[sprites]]
name = 'corner_bottomleft'
offset = [
    0,
    0,
]
texture = 'boneyard/cornerbottomleft.png'
attributes = []

[[sprites]]
name = 'player'
offset = [
    0,
    0,
]
texture = 'spirit.png'
attributes = ['player']

[[sprites]]
name = 'center_ground_nonsolid'
offset = [
    0,
    0,
]
texture = 'boneyard/middlemiddle.png'
attributes = []

[[sprites]]
name = 'center_ground_solid'
offset = [
    0,
    0,
]
texture = 'boneyard/middlemiddle.png'
attributes = ['solid']

[[sprites]]
name = 'death'
offset = [
    0,
    0,
]
texture = 'blank.png'
attributes = ['deadly']

[[sprites]]
name = 'elevator_secondary'
offset = [
    0,
    0,
]
texture = 'boneyard/middlemiddle.png'
attributes = [
    'moving(up,12,15)',
    'solid',
]

[[sprites]]
name = 'middle_ground'
offset = [
    0,
    0,
]
texture = 'boneyard/topmiddle.png'
attributes = ['solid']

[[sprites]]
name = 'trans_to_exit'
offset = [
    0,
    0,
]
texture = 'blank.png'
attributes = ['trans(1)']

[[sprites]]
name = 'ground_topright'
offset = [
    0,
    0,
]
texture = 'boneyard/topright.png'
attributes = ['solid']

[[sprites]]
name = 'moving_right_slow'
offset = [
    0,
    0,
]
texture = 'boneyard/topmiddle.png'
attributes = [
    'moving(right,5,5)',
    'solid',
]

[[sprites]]
name = 'ground_topleft'
offset = [
    0,
    0,
]
texture = 'boneyard/topleft.png'
attributes = ['solid']

[[sprites]]
name = 'ground_bottomleft'
offset = [
    0,
    0,
]
texture = 'boneyard/bottomleft.png'
attributes = ['solid']

[[sprites]]
name = 'ground_bottombottom'
offset = [
    0,
    0,
]
texture = 'boneyard/bottommiddle.png'
attributes = ['solid']

[[sprites]]
name = 'moving_left_slow'
offset = [
    0,
    0,
]
texture = 'boneyard/topmiddle.png'
attributes = [
    'solid',
    'moving(left,5,5)',
]

[[sprites]]
name = 'ground_middleright'
offset = [
    0,
    0,
]
texture = 'boneyard/middleright.png'
attributes = ['solid']

[[sprites]]
name = 'corner_bottomright'
offset = [
    0,
    0,
]
texture = 'boneyard/cornerbottomright.png'
attributes = []

[[sprites]]
name = 'skull_down'
offset = [
    0,
    0,
]
texture = 'skull.png'
attributes = [
    'moving(down,4,4)',
    'solid',
    'deadly',
]

[[sprites]]
name = 'ground_bottomright'
offset = [
    0,
    0,
]
texture = 'boneyard/bottomright.png'
attributes = ['solid']

[[sprites]]
name = 'ground_middleleft'
offset = [
    0,
    0,
]
texture = 'boneyard/middleleft.png'
attributes = ['solid']
