name = 'Picking up Speed'
music = 'walkintherain.ogg'

[[sprites]]
name = 'center_ground_nonsolid'
offset = [
    0,
    0,
]
texture = 'boneyard/middlemiddle.png'
attributes = []

[[sprites]]
name = 'player'
offset = [
    0,
    0,
]
texture = 'spirit.png'
attributes = ['player']

[[sprites]]
name = 'temple_middleright'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/middleright.png'
attributes = ['solid']

[[sprites]]
name = 'temple_bottomright'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/bottomright.png'
attributes = ['solid']

[[sprites]]
name = 'checkpoint'
offset = [
    0,
    0,
]
texture = 'checkpoint.png'
attributes = ['checkpoint(0,0,0)']

[[sprites]]
name = 'temple_rowmiddle'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowmiddle.png'
attributes = ['solid']

[[sprites]]
name = 'temple_rowright'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowright.png'
attributes = ['solid']

[[sprites]]
name = 'ground_topright'
offset = [
    0,
    0,
]
texture = 'boneyard/topright.png'
attributes = ['solid']

[[sprites]]
name = 'ground_middleright'
offset = [
    0,
    0,
]
texture = 'boneyard/middleright.png'
attributes = ['solid']

[[sprites]]
name = 'goal'
offset = [
    0,
    0,
]
texture = 'checkpoint.png'
attributes = ['goal(0)']

[[sprites]]
name = 'temple_topright'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/topright.png'
attributes = ['solid']

[[sprites]]
name = 'temple_bottomleft'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/bottomleft.png'
attributes = ['solid']

[[sprites]]
name = 'moving_right_slow_right'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowright.png'
attributes = [
    'moving(right,5,5)',
    'solid',
]

[[sprites]]
name = 'temple_columnmiddle'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/columnmiddle.png'
attributes = []

[[sprites]]
name = 'skull_down'
offset = [
    0,
    0,
]
texture = 'boneyard/spikefloat.png'
attributes = [
    'moving(down,4,4)',
    'solid',
    'deadly',
]

[[sprites]]
name = 'temple_topmiddle'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/topmiddle.png'
attributes = ['solid']

[[sprites]]
name = 'spikeleft'
offset = [
    0,
    0,
]
texture = 'boneyard/spikeleft.png'
attributes = ['deadly']

[[sprites]]
name = 'temple_middlemiddle'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/middlemiddle.png'
attributes = []

[[sprites]]
name = 'temple_rowleft'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowleft.png'
attributes = ['solid']

[[sprites]]
name = 'give_dash'
offset = [
    0,
    0,
]
texture = 'checkpoint.png'
attributes = ['give(dash)']

[[sprites]]
name = 'middle_ground'
offset = [
    0,
    0,
]
texture = 'boneyard/topmiddle.png'
attributes = ['solid']

[[sprites]]
name = 'temple_columntop'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/columntop.png'
attributes = ['solid']

[[sprites]]
name = 'checkpoint1'
offset = [
    0,
    0,
]
texture = 'checkpoint.png'
attributes = ['checkpoint(1,0,0)']

[[sprites]]
name = 'spikedown'
offset = [
    0,
    0,
]
texture = 'boneyard/spikedown.png'
attributes = ['deadly']

[[sprites]]
name = 'temple_bottommiddle'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/bottommiddle.png'
attributes = ['solid']

[[sprites]]
name = 'temple_topleft'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/topleft.png'
attributes = ['solid']

[[sprites]]
name = 'temple_middleleft'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/middleleft.png'
attributes = ['solid']

[[sprites]]
name = 'moving_right_slow_left'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowleft.png'
attributes = [
    'moving(right,5,5)',
    'solid',
]

[[sprites]]
name = 'spikeright'
offset = [
    0,
    0,
]
texture = 'boneyard/spikeright.png'
attributes = ['deadly']

[[sprites]]
name = 'moving_right_slow'
offset = [
    0,
    0,
]
texture = 'boneyardtemple/rowmiddle.png'
attributes = [
    'moving(right,5,5)',
    'solid',
]

[[sprites]]
name = 'spikeup'
offset = [
    0,
    0,
]
texture = 'boneyard/spikeup.png'
attributes = ['deadly']
