version = 1

[[sprites]]
name = "boneyard_ground_middle"
sprite_type = "solid"
offset_x = 0
offset_y = 0
texture = "sprites/boneyard_middle.png"

[[sprites]]
name = "player"
sprite_type = "player"
offset_x = 0
offset_y = 0
texture = "sprites/spirit.png"

[[sprites]]
name = "trail"
sprite_type = "trails"
offset_x = 0
offset_y = 0
texture = "sprites/trails.png"

[[sprites]]
name = "moving_platform_right_slow"
sprite_type = "moving_platform_right_slow"
offset_x = 0
offset_y = 0
texture = "sprites/boneyard_middle.png"
