version = 1

[[types]]
id = "solid"
attributes = [
  "solid"
]

[[types]]
id = "passthrough"
attributes = []

[[types]]
id = "player"
attributes = [
  "player"
]

[[types]]
id = "trails"
attributes = [
  "trails"
]

[[types]]
id = "moving_platform_right_slow"
attributes = [
  "solid",
  "moving(0, 6, 8)"
]

[[types]]
id = "moving_platform_left_slow"
attributes = [
  "solid",
  "moving(2, 6, 8)"
]

[[types]]
id = "moving_platform_up_slow"
attributes = [
  "solid",
  "moving(3, 8, 8)"
]

[[types]]
id = "death"
attributes = [
  "deadly"
]

[[types]]
id = "checkpoint"
attributes = [
  "checkpoint(0,0)"
]

[[types]]
id = "moving_death_vertical_slow"
attributes = [
  "moving(1, 5, 3)",
  "deadly",
]
