version = 1

[[types]]
id = "solid"
attributes = [
  "solid"
]

[[types]]
id = "passthrough"
attributes = []

[[types]]
id = "player"
attributes = [
  "player"
]

[[types]]
id = "trails"
attributes = [
  "trails"
]

[[types]]
id = "moving_platform_right_slow"
attributes = [
  "solid",
  "moving(0, 1, 5)"
]
