name: Build Game

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always
  ITCH_USERNAME: alumux
  ITCH_GAME_ID: temple

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev libxcb-xfixes0-dev libxcb-shape0-dev cmake mingw-w64 zip
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Windows Target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Get Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Setup Cache
      uses: Swatinem/rust-cache@v1
    - name: Build Windows Game
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./install_windows_client.sh
    - name: Publish to Itch.io
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
        gameData: windows
        itchUsername: ${{ env.ITCH_USERNAME }}
        itchGameId: ${{ env.ITCH_GAME_ID }}
        buildNumber: ${{ steps.get_version.outputs.VERSION }}
        buildChannel: windows
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev libxcb-xfixes0-dev libxcb-shape0-dev cmake mingw-w64 zip
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Get Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Setup Cache
      uses: Swatinem/rust-cache@v1
    - name: Build Linux Game
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: ./install_linux_client.sh
    - name: Publish to Itch.io
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
        gameData: linux
        itchUsername: ${{ env.ITCH_USERNAME }}
        itchGameId: ${{ env.ITCH_GAME_ID }}
        buildNumber: ${{ steps.get_version.outputs.VERSION }}
        buildChannel: linux
