name: Publish Code Coverage

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Cinstrument-coverage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Download grcov
      run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
    - name: Build Project
      run: cargo build
    - name: Run tests
      run: LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
    - name: Generate report file
      run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Publish to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./lcov.info
        flags: unittests
        name: github-actions-publish
        fail_ci_if_error: true
        verbose: true
