name: Publish Rustdoc

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get install -y libasound2-dev libudev-dev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-02-17
        override: true
    - name: Build Docs
      run: cargo doc --quiet --bin temple
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: target/doc
